### PR TITLE
Add support for django 3.0

### PR DESCRIPTION
**Pull request by yakky**
* [x] Replace ugettext_lazy with gettext_lazy when running on python 3
* [ ] Manual test paths not covered by test suite

### CODE REVIEW

**Comment by bunchesofdonald** [comment]
@yakky Anything I can do to help push this PR along? This is the last blocker for us to upgrade to Django 3.

**Comment by yakky** [comment]
@bunchesofdonald I just need to run it to cover code paths not included in tests
Any additional review, tests will help!

**Comment by c0d5x** [comment]
Could this be merged?

**Comment by izimobil** [comment]
Merged, thank you very much @yakky

**Pull request merged**
