### PR TITLE
Updates for Django 2.x

### LINKED ISSUE #88: Django 3 deprecation warning on 'load staticfiles'
With Django 2.1.4, I get the following deprecation warning:
`
django.utils.deprecation.RemovedInDjango30Warning: {% load staticfiles %} is deprecated in favor of {% load static %}
`
The cause seems to be css.html for dashboard and menu, which contains 'staticfiles'

### LINKED ISSUE #92: Admin layout broken in Django 2.2
In Django 2.2 the admin menu is no longer shown properly.
This happens due to this CSS rule in Django's default styling: `#header { display: flex }`.

I've tried tweaking this, but my flexbox knowledge is limited here, so I hope someone could look into this.

### PR DESCRIPTION
**Pull request by AngellusMortis**
* Drops support for versions before 1.11
* Adds Django 2.1,2.2 and Python 3.7 to tox/travis
* Fixes tests and deprecations (fixes #88)
* Fixes CSS for Django 2.2 (fixes #92)

### CODE REVIEW

**Comment by izimobil** [comment]
Nice work, thanks.

Can you please also update the documentation (there are references to django <= 1.8, that are no longer necessary now).

Also, a request: please next time try to separate pep8 / style fixes (which are always nice !) from code related to the pull request itself, it will be easier for future maintenance.

Thanks again.

**Comment by AngellusMortis** [comment]
> Also, a request: please next time try to separate pep8 / style fixes (which are always nice !) from code related to the pull request itself, it will be easier for future maintenance.

Sorry! I use `black` directly in my editor. So they just kind of happen. Would you be objected to me just auto-formatting the whole project in a single PR?

**Comment by izimobil** [comment]
> Sorry! I use `black` directly in my editor. So they just kind of happen. Would you be objected to me just auto-formatting the whole project in a single PR?

OK for me, and maybe add the .flake8 file for other contributors ? (and maybe a note in https://github.com/django-admin-tools/django-admin-tools/blob/master/docs/contributing.rst or post commit hook, I'm not sure...).

**Comment by AngellusMortis** [comment]
> OK for me, and maybe add the .flake8 file for other contributors ?

I can make another pass for linting/formatting. I just updated the docs to note that 1.11 is required now, also removes from <1.11 shims as well.

I made an assumption on the next version release in a couple of stops in the docs. I _assume_ the next version would be 0.9.0.

**Comment by izimobil** [comment]
Merged, thanks !

After some thinking, I think the best is that you disable black when working on DAT (and other opensource projects), because IIRC it will also reformat valid pep8 code, and it really makes the review of changes painful.

Regards.

**Comment by AngellusMortis** [comment]
It reformats code to valid PEP8 code, but yeah, you are right, it can reformat code that is already valid. It is very opinionated. I know a lot of my co-workers still have a bit of trouble liking it, most people have decided it is more helpful than anything since it consistent and just formats the code for you. 

For my other project I use it and I just have a `tox` env that runs the check to make sure you have ran it. `black` has grown quite a bit in popularity. `pytest` and `tox` uses it is and the core Python and Django devs have both said they are going to use it in the future for new stuff. It is even under the official umbrella of PSF now as well.

**Comment by izimobil** [comment]
I understand, but I don't want contributors to be forced to use an external tool as long as it's valid PEP8 code, and TBH my main concern is having to figure out PEP8 changes and real code changes in reviews. So let's skip "black" for now (which is a great tool BTW).

**Comment by AngellusMortis** [comment]
Fair enough.

**Pull request merged**
